# Generated by Django 2.2.3 on 2019-07-21 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_head',
        ),
        migrations.AddField(
            model_name='group',
            name='headman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Student'),
        ),
    ]
