# Generated by Django 2.2.3 on 2019-07-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20190721_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_d',
            field=models.DateField(),
        ),
    ]
