# Generated by Django 2.2.3 on 2019-08-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20190802_1423'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogTable',
            new_name='Log',
        ),
    ]
