# Generated by Django 2.2.3 on 2019-07-21 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='username must contain ascii letters, numbers and (-_.)', regex='^[a-zA-Z0-9.-_]*$')]),
        ),
    ]
